name: sf_urban_health
version: 1.0.0
config-version: 2

profile: sf_urban_health

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  sf_urban_health:
    staging:
      +schema: staging
      +materialized: view
      +tags: ['daily']
    intermediate:
      +schema: intermediate
      +materialized: view
      +tags: ['daily']
    marts:
      +schema: marts
      +materialized: table
      +tags: ['daily']
    metadata:
      +schema: metadata
      +materialized: view
      +tags: ['daily']

  elementary:
    +schema: elementary

tests:
  sf_urban_health:
    +severity: warn
