-- Run this after confirming METADATA.AIRFLOW_DAG_RUNS and
-- METADATA.AIRFLOW_TASK_INSTANCES are created and receiving data.
USE DATABASE SF_URBAN_HEALTH;

DROP TABLE IF EXISTS RAW.AIRFLOW_DAG_RUNS;
DROP TABLE IF EXISTS RAW.AIRFLOW_TASK_INSTANCES;
